
"use client";

import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { PopOutButton } from './pop-out-button';
import { Beaker, GripVertical, EyeOff, Save } from 'lucide-react';
import { Textarea } from '../ui/textarea';
import { useToast } from '@/hooks/use-toast';
import { Label } from '../ui/label';

interface SandboxCardProps {
    onPopOut?: () => void;
    isPoppedOut?: boolean;
    onHide?: () => void;
    dragHandleProps?: any;
    isPreview?: boolean;
}

export function SandboxCard({ onPopOut, isPoppedOut = false, onHide, dragHandleProps, isPreview }: SandboxCardProps) {
    const [code, setCode] = useState('');
    const { toast } = useToast();

    const handleSave = () => {
        // In a real dynamic environment, this would trigger a build or update.
        // For our purposes, this "saves" the code to the component's state.
        // The next step would be to tell the AI assistant to apply this code permanently.
        toast({
            title: 'Code Saved to Sandbox',
            description: 'Your code is now in the sandbox. Ask the AI to apply it permanently.',
        });
    };

    return (
        <Card className="flex flex-col h-full bg-secondary/20">
            <CardHeader>
                <div className="flex justify-between items-start">
                    <div className="flex items-center gap-2 flex-grow">
                        <Button variant="ghost" size="icon" {...dragHandleProps} className="cursor-grab p-1 h-auto w-auto text-secondary">
                            <GripVertical />
                        </Button>
                        <div className="flex-grow">
                            <CardTitle className="flex items-center gap-2">
                                <Beaker className="h-6 w-6 text-primary" />
                                AI Sandbox
                            </CardTitle>
                            <CardDescription>
                                A place to test AI-generated components.
                            </CardDescription>
                        </div>
                    </div>
                    <div className="flex items-center">
                        {!isPoppedOut && onHide && (
                            <Button variant="ghost" size="icon" onClick={onHide} className="text-destructive">
                                <EyeOff className="h-4 w-4" />
                            </Button>
                        )}
                        {!isPoppedOut && onPopOut && <PopOutButton onClick={onPopOut} />}
                    </div>
                </div>
            </CardHeader>
            <CardContent className="flex-grow flex flex-col gap-4">
                <div className="space-y-2 flex-grow flex flex-col">
                    <Label htmlFor="code-input">Paste Generated Code Here</Label>
                    <Textarea
                        id="code-input"
                        placeholder="Paste the .tsx code generated by Cipher here..."
                        className="flex-grow font-mono text-xs"
                        value={code}
                        onChange={(e) => setCode(e.target.value)}
                    />
                </div>
                <div className="flex justify-end">
                    <Button onClick={handleSave}>
                        <Save className="mr-2 h-4 w-4" />
                        Save Code to Sandbox
                    </Button>
                </div>
            </CardContent>
        </Card>
    );
}
