"use client";

import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { PopOutButton } from './pop-out-button';
import { Beaker, GripVertical, EyeOff, Save, Loader2 } from 'lucide-react';
import { Textarea } from '../ui/textarea';
import { useToast } from '@/hooks/use-toast';
import { Label } from '../ui/label';
import { saveToSandbox } from '@/ai/flows/save-to-sandbox-flow';

interface SandboxCardProps {
    onPopOut?: () => void;
    isPoppedOut?: boolean;
    onHide?: () => void;
    dragHandleProps?: any;
    isPreview?: boolean;
}

export function SandboxCard({ onPopOut, isPoppedOut = false, onHide, dragHandleProps, isPreview }: SandboxCardProps) {
    const [code, setCode] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const { toast } = useToast();

    const handleSave = async () => {
        if (!code) {
            toast({
                title: 'Nothing to Save',
                description: 'Please paste some code into the text area first.',
                variant: 'destructive'
            });
            return;
        }
        setIsLoading(true);
        try {
            const result = await saveToSandbox({
                code,
                filePath: 'src/components/sandbox/generated-card.tsx'
            });

            if (result.success) {
                toast({
                    title: 'Code Saved to Sandbox',
                    description: 'Your code has been written to the sandbox file. A page refresh may be needed to see changes.',
                });
            } else {
                throw new Error(result.message);
            }
        } catch (error) {
            const err = error as Error;
            toast({
                title: 'Save Failed',
                description: err.message,
                variant: 'destructive'
            });
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <Card className="flex flex-col h-full bg-secondary/20">
            <CardHeader>
                <div className="flex justify-between items-start">
                    <div className="flex items-center gap-2 flex-grow">
                        <Button variant="ghost" size="icon" {...dragHandleProps} className="cursor-grab p-1 h-auto w-auto text-secondary">
                            <GripVertical />
                        </Button>
                        <div className="flex-grow">
                            <CardTitle className="flex items-center gap-2">
                                <Beaker className="h-6 w-6 text-primary" />
                                AI Sandbox
                            </CardTitle>
                            <CardDescription>
                                A place to test AI-generated components.
                            </CardDescription>
                        </div>
                    </div>
                    <div className="flex items-center">
                        {!isPoppedOut && onHide && (
                            <Button variant="ghost" size="icon" onClick={onHide} className="text-destructive">
                                <EyeOff className="h-4 w-4" />
                            </Button>
                        )}
                        {!isPoppedOut && onPopOut && <PopOutButton onClick={onPopOut} />}
                    </div>
                </div>
            </CardHeader>
            <CardContent className="flex-grow flex flex-col gap-4">
                <div className="space-y-2 flex-grow flex flex-col">
                    <Label htmlFor="code-input">Paste Generated Code Here</Label>
                    <Textarea
                        id="code-input"
                        placeholder="Paste the .tsx code generated by Cipher here..."
                        className="flex-grow font-mono text-xs"
                        value={code}
                        onChange={(e) => setCode(e.target.value)}
                    />
                </div>
                <div className="flex justify-end">
                    <Button onClick={handleSave} disabled={isLoading}>
                        {isLoading ? <Loader2 className="mr-2 h-4 w-4 animate-spin"/> : <Save className="mr-2 h-4 w-4" />}
                        Save Code to Sandbox
                    </Button>
                </div>
            </CardContent>
        </Card>
    );
}
